CREATE TABLE lists (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE todos (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE,
  completed BOOLEAN NOT NULL DEFAULT false,
  list_id INTEGER NOT NULL REFERENCES lists (id)
);
